version: '2'
services:

  web:
    image: nginx:1.10
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    ports:
      - 8080:80
    links:
      - php
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./website:/var/www/website
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.3
    volumes:
      - ./migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
    ports:
      - 3306:3306
